remove unneeded `UNUserNotificationCenter requestAuthorizationWithOptions`
bitsydarel/flutter_app_badger pull request #1
Opened 2024-03-06 12:01 UTC by EvGeniyLell

2024-03-07 16:10 UTC, bitsydarel requested changes

2024-03-07 16:10 UTC, bitsydarel commented on pubspec.yaml
> +version: 1.5.2
Please update the release notes

2024-03-07 16:10 UTC, bitsydarel commented on pubspec.yaml
> +  sdk: ">=3.3.0 <4.0.0"
Since this is a third party plugin,, changing the minimum SDKs is not recommended.

The goal of forks is to later be migrated to the main repository.

2024-03-15 11:41 UTC, EvGeniyLell commented on pubspec.yaml
> +version: 1.5.2
done

2024-03-19 20:46 UTC, merged